Sprint 3/step 1
leksGoDev/burger-rest pull request #5
Opened 2022-11-10 20:08 UTC by leksGoDev

2022-11-10 21:52 UTC, randomroot requested changes
**Доброго времени суток!**

Вы проделали **прекрасную** работу по добавлению роутинга и авторизации в ваш проект, код очень лаконичный и хорошо типизирован, корректная работа с редакс тулкитом, удобные хуки, вкупе с универсальной формой, проверяется валидность токенов и их рефреш, так держать 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно изучить комментарии, описанные в рамках ревью, и провести необходимые изменения, обратив особое внимание на следующие моменты:

**Нужно исправить:**

- Кнопка удаления должна присутствовать только у соусов/начинок бургера, у булки такой функционал не предусмотрен, согласно дизайну;
- После сохранения формы пользователя с новым паролем не пропадают кнопки "Сохранить" и "Отмена";
- Пути `/login`, `/register`, `/reset-password` и `/forgot-password` должны быть доступны только для анонимных пользователей. Авторизованных следует перенаправлять на главный экран приложения.
- У пользователя есть возможность отправить форму со всеми пустыми значениями, следует добавить минимальное ограничение для имени и логина;
- При нажатии на один из табов для перехода к разделам ингредиентов осуществляется скролл экрана вниз и хедер перестает быть доступным (1920x1000, Chrome). В полноэкранном режиме всё нормально, следует сделать этот момент более адаптивным;
- Модальное окно следует оставить универсальным решением, не целесообразно внутри него хардкодить стилизацию, этот момент должен быть на стороне содержимого;
- Использование `null-assertion` считается не совсем удачной практикой, следует минимизировать её использование или полностью отказаться, чтобы избежать побочных эффектов, связанных с возможностью появления пустых объектов при ожидании корректных;
- Следует вынести время жизни токенов в отдельные константы;


**Можно улучшить:**

- На время создания заказа имеет смысл блокировать кнопку оформления или отображать прелоадер, чтобы пользователь не смог бесконечно нажимать и отправлять запросы, т.к. сейчас не очевидно, отправляется заказ или нет;

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**.

---

**Успешного вам рефакторинга и хорошего настроения!** 🐈

2022-11-10 21:52 UTC, randomroot commented on src/components/app-header/app-header-element/app-header-element.tsx
> +            <Link to={linkRoute} className={styles.placement}>
🟡 **Можно улучшить:**

Для подсветки активности ссылки имеет смысл использовать `NavLink` вместо `Link`, там есть полезные пропсы, которые позволят упростить ваш код (см. https://v5.reactrouter.com/web/api/NavLink)

2022-11-10 21:52 UTC, randomroot commented on src/components/app/app.tsx
> +                <Route exact path="/login" component={Login} />
🔴 **Нужно исправить:**

Пути `/login`, `/register`, `/reset-password` и `/forgot-password` должны быть доступны только для анонимных пользователей. Авторизованных следует перенаправлять на главный экран приложения.

🟡 **Можно улучшить:**

Для реализации описанного выше функционала следует либо cоздать отдельный компонент `OnlyUnAuthRoute`, по аналогии c `ProtectedRoute`, который будет защищать эти страницы от авторизированных пользователей или доработать компонент `ProtectedRoute`  передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2022-11-10 21:52 UTC, randomroot commented on src/components/auth/auth-form/form-input/form-input.tsx
> +interface Props extends InputData {}
🟡 **Можно улучшить:**

Т.к. вы не добавляете дополнительных пропсов к интерфейсу `InputData`, то можно использовать последний напрямую, без создания `Props`.

Аналогично и в других файлах, где есть **пустые** интерфейсы

2022-11-10 21:52 UTC, randomroot commented on src/components/ingredient-details/ingredient-details.tsx
> +                        <IngredientDetailsArticle name="Калории,ккал" value={calories} width={120} />
🟡 **Можно улучшить:**

Ширину каждого элемента задавать вручную не совсем удачная практика, лучше воспользоваться возможностями `flex` или `grid` разметки для автоматического позиционирования элементов

2022-11-10 21:52 UTC, randomroot commented on src/components/modal/modal.tsx
> +                    className={type === ModalType.Ingredient
🔴 **Нужно исправить:**

Стилизация модального окна, как контейнера, не должна отличаться в зависимости от его содержания. Будет довольно сложно поддерживать код, если таких типов станет много, поэтому этот момент лучше перенести непосредственно в содержимое окна.

2022-11-10 21:52 UTC, randomroot commented on src/pages/profile/profile-information/profile-information.tsx
> +    const [email, setEmail] = useState(user!.email);
🔴 **Нужно исправить:**

Использование null-assertion считается не совсем удачной практикой, т.к. возможны побочные эффекты в случае, если значение окажется пустым, плюс это ухудшает стабильность вашего кода. Поэтому, следует отказаться **здесь и далее по коду** от таких выражений. (см. https://typescript-eslint.io/rules/no-non-null-assertion/)

В данном случае, поле `user` может оказаться пустым, если данные о пользователе еще не были загружены с сервера.

2022-11-10 21:52 UTC, randomroot commented on src/components/auth/auth-form/auth-form.tsx
> +const AuthForm: FC<Props> = ({ title, buttonText, inputs, linkRows, onSubmit }) => {
🟡 **Можно улучшить:**

Имеет смысл сменить название компонента на более универсальное, т.к. оно в данным момент представляет собой универсальную форму

2022-11-10 21:52 UTC, randomroot commented on src/services/api/cookie.ts
> +        setCookie("accessToken", token, 1200);
🔴 **Нужно исправить:**

Время жизни токенов **здесь и ниже** следует выделить в отдельные константы

2022-11-11 00:12 UTC, leksGoDev commented on src/components/app-header/app-header-element/app-header-element.tsx
> +            <Link to={linkRoute} className={styles.placement}>
Пробовал сразу через колбэк в NavLink className, но ни в какую не работал. Голову сломал что не так. В итоге в навигации профиля сделал через className + activeClassName, а тут решил через Link и пропсы.

2022-11-12 01:19 UTC, leksGoDev commented on src/components/ingredient-details/ingredient-details.tsx
> +                        <IngredientDetailsArticle name="Калории,ккал" value={calories} width={120} />
На макете ширина 4 блоков фиксирована (120px, 112px, 112px, 112px) вне зависимости от контента.

2022-11-12 16:54 UTC, randomroot requested changes
**Здравствуйте!**

Вы внесли немало правок для исправления выявленных в работе неточностей, а также улучшили качество своего кода, добавили дополнительно современный AbortController, однако для окончательного завершения работы над спринтом вам следует провести еще один ряд корректировок, связанных со следующими моментами:

- У пользователя есть возможность отправить форму со всеми пустыми значениями, следует добавить минимальное ограничение для имени и логина (https://disk.yandex.ru/i/an_oI5TWnwtedg). Параметр `minLength`, добавленный вами, это правильное направление, однако валидация не будет происходить для пустых значений, согласно спецификации (cм. https://www.w3.org/TR/html5/forms.html#setting-minimum-input-length-requirements:-the-minlength-attribute);
- При нажатии на табы "соус" или "начинки" для перехода к разделам ингредиентов осуществляется скролл экрана вниз и хедер перестает быть доступным, у таба "булки" всё хорошо (1920x1000, Chrome).  (https://disk.yandex.ru/i/KiBihyxc5Ed_Og) (https://disk.yandex.ru/i/JK2h2mdRXfePEA);

**Хороших вам выходных!** 🐈

2022-11-12 16:54 UTC, randomroot commented on src/components/app/app.tsx
> +        const controller = new AbortController();
🟢 **Отлично:**

Интересное и современное решение по прерыванию запросов 👍

2022-11-12 16:54 UTC, randomroot commented on src/components/order-details/order-details.tsx
> +        (component: ReactNode) => true ? // Временный мок для стиля в режиме модалки
🟡 **Можно улучшить:**

Не совсем понятно, что подразумевается под "режимом модалки", но если временный мок более не требуется, то его следует удалить. Данный компонент может оказаться только внутри модального окна

2022-11-12 21:17 UTC, leksGoDev commented on src/components/order-details/order-details.tsx
> +        (component: ReactNode) => true ? // Временный мок для стиля в режиме модалки
Судя по макету OrderDetails в следующем спринте надо будет сделать тоже отдельной страницей (кроме модального окна). В текущем спринте нет такой задачи.

2022-11-13 06:56 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, так держать👍

Замечательная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2022-11-13 06:56 UTC, randomroot commented on src/pages/profile/profile-information/profile-information.tsx
> +    const isSubmitDisabled = useCallback(
🟡 **Можно улучшить:**

Здесь лучше использовать `useMemo` для вычисления значения константы или поменять наименование переменной для `useCallback` по правилом нейминга функций (`is` не подходит)

2022-11-13 22:14 UTC, merged